### ISSUE TITLE
Max Number of Shapes Renderable with Mesh

### ISSUE THREAD

**Issue by vinceniko** [hecrj/coffee#87]
When rendering over 1k PolyLines on a single mesh, as the number of lines increased, I saw other lines disappear and a gradient streak appear, stretching from the top-left corner towards the middle where some line was rendered. See the below image:

<img width="947" alt="Screen Shot 2019-08-31 at 11 16 15 PM" src="https://user-images.githubusercontent.com/30331170/64071295-5907bd80-cc45-11e9-8bae-0d3d6110b8ce.png">

Given that my code works for a lower number of lines perfectly, I tried to allocate more than 1 mesh for drawing all the lines. Distributing the total number of lines among several meshes seems to have fixed the bug. I assume that this bug relates to some max bound for how many shapes a mesh can hold, but have not been able to find evidence of that in the documentation. If this bound does exist, it should be documented.

**Comment by hecrj** [comment]
Is this on Vulkan, Metal, or Direct3D? I think this is most probably fixed in `master` by https://github.com/hecrj/coffee/commit/79651405673ecd16da21b887a622f6650b29f38f.

I backported the fix and released a new patch version: https://github.com/hecrj/coffee/releases/tag/0.3.2. Let me know if it fixes the issue!

**Comment by vinceniko** [comment]
Metal. Will try the fix and report back. Thanks

**Comment by vinceniko** [comment]
Seems fixed on my end. Thanks for the fast turn around!

**Comment by hecrj** [comment]
Awesome! I've been meaning to backport those fixes for a while :sweat_smile:

Thank you for the detailed report!

**Comment by vinceniko** [comment]
It seems that the issue of losing vertices is still present, though the situation improved since the last fix as it takes more of them being drawn to notice this. I'm noticing a loss of Polylines when more than ~16,400 are drawn. The loss is fairly noticeable when ~16,800 are drawn. There is no gradient streak this time. If lines are distributed over multiple meshes then the issue is improved i.e. doubling the number of meshes drawn shows a loss of lines at ~16,40 x 2 lines.

**Comment by hecrj** [comment]
Not sure what i couldt be now. I will take a look.

By any chance, could you provide an SSCCE so I can easily reproduce the issue?

**Comment by hecrj** [comment]
I have been able to reproduce the issue.

Here is an SSCCE:

```rust
use coffee::graphics::{
    Color, Frame, HorizontalAlignment, Mesh, Point, Shape, Window,
    WindowSettings,
};
use coffee::load::Task;
use coffee::ui::{
    slider, Column, Element, Justify, Renderer, Slider, Text, UserInterface,
};
use coffee::{Game, Result, Timer};

fn main() -> Result<()> {
    <Lines as UserInterface>::run(WindowSettings {
        title: String::from("Lines - Coffee"),
        size: (1280, 1024),
        resizable: false,
        fullscreen: false,
    })
}

struct Lines {
    mesh: Mesh,
    amount: u32,
    slider: slider::State,
}

impl Game for Lines {
    type Input = ();
    type LoadingScreen = ();

    fn load(_window: &Window) -> Task<Self> {
        Task::succeed(|| Lines {
            mesh: Mesh::new(),
            amount: 0,
            slider: slider::State::new(),
        })
    }

    fn draw(&mut self, frame: &mut Frame<'_>, _timer: &Timer) {
        frame.clear(Color::BLACK);

        self.mesh.draw(&mut frame.as_target());
    }
}

enum Message {
    AmountChanged(f32),
}

impl UserInterface for Lines {
    type Message = Message;
    type Renderer = Renderer;

    fn react(&mut self, message: Message, window: &mut Window) {
        match message {
            Message::AmountChanged(amount) => {
                self.mesh = Mesh::new();
                self.amount = amount.round() as u32;

                for i in 0..=self.amount {
                    let x = (i % window.width() as u32) as f32;
                    let y = (i / window.width() as u32) as f32;

                    self.mesh.stroke(
                        Shape::Polyline {
                            points: vec![
                                Point::new(x, y),
                                Point::new(x + 3.0, y),
                            ],
                        },
                        Color::WHITE,
                        2.0,
                    );
                }
            }
        }
    }

    fn layout(&mut self, window: &Window) -> Element<Message> {
        Column::new()
            .width(window.width() as u32)
            .height(window.height() as u32)
            .justify_content(Justify::End)
            .padding(50)
            .spacing(20)
            .push(Slider::new(
                &mut self.slider,
                0.0..=20_000.0,
                self.amount as f32,
                Message::AmountChanged,
            ))
            .push(
                Text::new(&self.amount.to_string())
                    .horizontal_alignment(HorizontalAlignment::Center),
            )
            .into()
    }
}
```

The example renders lines to fill the screen. As you described, the mesh strops drawing after reaching ~16,400 lines.

**Comment by hecrj** [comment]
I have found the issue:

`Mesh` is currently using an index buffer of `u16` values. Each polyline has 4 vertices, so the total amount of polylines supported by the current `Mesh` implementation is `2**16 / 4 = 16384`.

The most simple fix is to promote the indices to `u32`.

**Comment by vinceniko** [comment]
Great thanks! I assume this wouldn't impact performance in any meaningful way?

**Comment by hecrj** [comment]
It's hard to say without actual benchmarks (we should tackle #13 soon), but my intuition says the impact should be mostly negligible for most workloads/platforms.

In any case, if performance is actually noticeably worse, we could try to improve it by using different strategies (automatically batching huge meshes, etc.) without any breaking changes.
